CUBRID=/home/cubrid/CUBRID
CUBRID_DATABASES=$CUBRID/databases/
export CUBRID CUBRID_DATABASES

LD_LIBRARY_PATH=$CUBRID/lib:$CUBRID/cci/lib:$LD_LIBRARY_PATH
PATH=$CUBRID/bin:/usr/sbin:$PATH
export LD_LIBRARY_PATH PATH

